### ISSUE TITLE
EAccessViolation during NPC Activity Maintenance on Raspbian

### ISSUE THREAD

**Issue by swarmdog** [rickparrish/Usurper#12]
I'm compiling on Raspbian (Pi 3B) with some changes to the build parameters (I've added these changes to my fork).  I am able to launch EDITOR and setup the game, and launch Usurper locally and play.  However during maintenance I get an access violation (exit code 217) during NPC Activity (24%).

Stack trace:
line 1960 of USURPER/NPCMAINT.PAS
line 1127 of USURPER/MAINT.PAS
line 695 of USURPER/USURPER.PAS

The error seems to be caused by this line:       raise_player(pl0^, npcnews, False, False, True, '');

**Comment by dan1982code** [comment]
Not sure if Rick is still active on BBS stuff, but I unfortunately can't find much time these days. At one point, a few years ago, I knew this code quite well and was fixing bugs all over the place. I never ran into this maintenance crash on Windows, but perhaps it is exposed by some combination of fpc flags.

**Comment by swarmdog** [comment]
Workaround: I am able to complete maintenance by deleting the default NPCs.  I suspect a particular NPC is causing this although it's hard to narrow it down.  If I find anything more specific I'll report back. 

My FPC defines are here: https://github.com/swarmdog/Usurper/blob/master/SOURCE/COMMON/DEFINES.INC

And my build parameters are here: 
https://github.com/swarmdog/Usurper/blob/master/SOURCE/BUILD-arm.sh

If anything jumps out at you as possibly causing a problem, let me know.
