### ISSUE TITLE
Scores file not showing players past level 20

### ISSUE THREAD

**Issue by rexhondo** [rickparrish/Usurper#15]
I have confirmed this bug when upgrading from v0.20 to v0.24. Thinking it may have been a side effect of upgrading, I installed fresh v0.24. Confirmed bug still exists. Trying to get around this, I installed v0.20 fresh and scores file now shows players past level 20.

I, personally, think this is a game breaking bug. With more than one player playing, being able to see scores is important, so we've reverted to v0.20 until the bug is fixed.

**Comment by CraigEMP** [comment]
Check my comment on issue #6.  I believe I've discovered the cause of the problem.
