### ISSUE TITLE
Keeping DOS versions in and after .24

### ISSUE THREAD

**Issue by CraigEMP** [rickparrish/Usurper#17]
There is still a DOS version present in Release v0.24, even though the changelog contains this note:

https://github.com/rickparrish/Usurper/blob/49152ae8d3af263d024b80b9b825c534c5943187/changelog.txt#L4

The reason I bring this up is because I happen to use the DOS version currently.  Since the switch to Lazarus/FPC, is there any chance of using ppcross8086.exe (or something) to keep a DOS version going?

A DOS version of Usurper is still highly desirable (for retro 16-bit BBS's, etc.).  I'd be willing to do the legwork to learn more about Lazarus and compile a DOS version containing all the current fixes, including the SortPl fix, with help from folks here who know the code best.

**Comment by rickparrish** [comment]
If you can get it to work, I'd be more than happy to accept your pull requests, or even give you direct access to the repository so you wouldn't be held up by me needing to accept anything.

**Comment by CraigEMP** [comment]
Well, assuming I'm taking the right approach by trying to compile using [ppcross8086](https://wiki.freepascal.org/DOS#Releases), the first thing it does is:

> Compile Project, OS: msdos, CPU: i8086, Target: C:\Users\craig\webstuff\bbsfiles\usurper\Usurper-0.24\bin\i8086-msdos\USURPER32.exe: Exit code 1, Errors: 1
> USURPER.PAS(39,17) Fatal: Cannot find Overlay used by Usurper of the Project Inspector.

This is where I stopped last time I tried.

**Comment by rickparrish** [comment]
Likely related to the Overlay unit, which was important for the original 16bit version to work within memory constraints, but is not needed/supported with FreePascal.

But if I understand correctly ppcross8086 compiles to 16bit, so it likely does become important again.

Looking at the link you gave, I wonder if the solution will be to remove the reference to the Overlay unit, and then use a different memory model or {$HUGECODE on}

**Comment by rickparrish** [comment]
GO32V2 builds are included now.
