### ISSUE TITLE
Teammate(s) still present for fights when chased away by dogs while beer stealing 

### ISSUE THREAD

**Issue by CraigEMP** [rickparrish/Usurper#18]
This one's kind of funny.  If you take a teammate beer stealing (under evil deeds), you can have them distract the dogs, giving you fewer dogs to worry about while you begin stealing barrels.

After you defeat the remaining dogs, and the innkeeper's sons start coming out to fight you, **your teammate is still there helping you fight them off**, even though he/she was chased away.  You'll see lines of text saying he/she is fighting and taking hits, then a line of text saying he/she just returned saying, "I finally managed to lose those dogs," and then continue fighting as though he/she never left.

I don't have a screenshot at the moment, but here are the steps to reproduce:
- Be a member of a team in the game.
- Go beer stealing.
- Select "Bring a teammate" when given the option of how to deal with the guard dogs.
- Watch the lines of text that follow.

**Comment by dan1982code** [comment]
Good one :) thanks!

I see what's happening and just tried to fix it.

Curious if this happened in 0.20 as well, or if this is a bug that I introduced somewhere along the line.

**Comment by dan1982code** [comment]
Just checked 0.20e and the logic for this part of beer-stealing seems to be messed-up there as well. So unless something weird (like uninitialized variables) made it work by chance in the past, my guess is that this was always broken.

I'm very surprised, though, and don't really trust myself on this! Seems like something that would have been caught and fixed many years before Jakob stopped.

**Comment by CraigEMP** [comment]
Yeah, I think it's always been there.  I have vague recollections of it happening to me and my friends back in the day. :)

Thanks for fixing!
