### ISSUE TITLE
Incorrect stats reported in EDITOR.EXE

### ISSUE THREAD

**Issue by CraigEMP** [rickparrish/Usurper#21]
![wrongstats](https://user-images.githubusercontent.com/12660452/86263364-209b7d80-bb8f-11ea-950b-edc905338c06.PNG)

Using the latest compiled DDPlus binaries, player stats in EDITOR don't match the stats in the game.

See the attached image.  Llwellyn is level 16 in the game, but EDITOR has him at level 32.  The rest of the stats are almost certainly wrong as well, for example the Hps of 1500.

**Comment by rickparrish** [comment]
@CraigEMP Thanks for reporting this.  Took me far too long to look into it, but the latest binaries in the master branch should now be fixed.

**Comment by CraigEMP** [comment]
Confirmed! Thanks.
