### ISSUE TITLE
Comments? Not showing up/Menu

### ISSUE THREAD

**Issue by Talmeron** [rickparrish/Usurper#7]
Not sure what it supposed to be there, but after your Status Screen after login there is nothing there. I type randomly and manage to get past it, but, a bug just the same. 

Unix/Ubuntu with Sychronet

**Comment by PaddyMac** [comment]
This issue has existed since the January 24, 2016 commit. I've just kind of put up with it because a CTRL-C will continue past the apparent lockup. At least that works in Syncterm, although I discovered that doesn't work with PuTTY. So some terminals may handle CTRL-C characters differently.

**Comment by dan1982code** [comment]
Hi all... is this the part where it expects you to press enter to continue? Does pressing questionmark at this stage do anything? Thanks!

**Comment by rickparrish** [comment]
After the status screen I see the Street Talk screen.  This is with the latest binaries I just pushed that fixed the double-output issue on Mystic, so maybe it also fixed this issue, or maybe it's a more subtle bug that is only triggered in some circumstances.

(Sorry for the super late reply, didn't notice people were submitting issues on any of my repositories until last week!)

**Comment by dan1982code** [comment]
Thanks, Rick! And good to hear from you. I'm still interested in helping here, as well.

**Comment by rickparrish** [comment]
Yeah I just got the itch to work on BBS stuff again the other day...started with some changes to LORD2, but then when I saw the Usurper issues I figured I should look into that first.

While cleaning up my working directory I came across the "20 bugs" document that you previously sent, so maybe we can work through more of the items on that list (I saw you already commented on and handled some of them, but didn't look closely to see what was left)
