### ISSUE TITLE
linux version maintenance

### ISSUE THREAD

**Issue by Ol-Father** [rickparrish/Usurper#9]
Maintenance does not appear to run properly on Linux.

```
root@NanoPi-NEO2:/mystic/DOORS/USURPER# ./USURPER /hmaint
Linux Detected

Maintenance not able to run! Players are reported ONLINE.
```

Have I missed a config?  thanks.

**Comment by rickparrish** [comment]
That error indicates one of the players is being reported as online.  Part of the maintenance should be to remove people from the ONLINERS.DAT file if they've been on for more than "maxtime", but without digging in I'm not sure where that variable comes from.

The quick fix should be to zero out the NODE/ONLINERS.DAT file, and then it won't think anybody is online.  Of course you won't want to do this unless everybody really is offline!
